sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    bucket-name: java-management-016
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: java-management-016
    access-key-secret: QjqIA4MRVplurQzEHrSx9jHFMbF3dJ

  wechat:
    appid: wx4cdddbcd89c97cd0
    secret: f98f650e1a47cc5d755c0a8e9c887cf6