sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    bucket-name: java-management-016
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: java-management-016
    access-key-secret: QjqIA4MRVplurQzEHrSx9jHFMbF3dJ

  wechat:
    appid: wx4cdddbcd89c97cd0
    secret: f98f650e1a47cc5d755c0a8e9c887cf6
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #privateKeyFilePath: classpath:cert/apiclient_key.pem
    apiV3Key: 32823456789012345678901234567890
    #weChatPayCertFilePath: classpath:cert/wechatpay_cert.pem
    notifyUrl: http://51962fcc.r22.cpolar.top/wechatpay/notify
    refundNotifyUrl: http://51962fcc.r22.cpolar.top/wechatpay/refundNotify

  shop:
    address: 杭州市钱塘区学源街168号

  baidu:
    ak: r9L6wrzjH2NWhRj77CT5OZb6xTK17CdD
